In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    'Student_ID': [1,2,3,4,5,6,7,8,9,10],
    'Math': [78,85,np.nan,90,120,65,70,200,88,76],
    'Science': [82,88,84,np.nan,91,67,73,95,89,300],
    'English': [75,80,78,85,88,np.nan,72,90,86,79],
    'Attendance': [85,90,88,92,95,80,85,110,87,89]
})

In [3]:
df.isnull().sum()

Student_ID    0
Math          1
Science       1
English       1
Attendance    0
dtype: int64

In [4]:
df = df.fillna(df.mean(numeric_only=True))

In [5]:
df.describe()

       Student_ID        Math     Science    English  Attendance
count    10.00000   10.000000   10.000000  10.000000   10.000000
mean      5.50000   96.888889  107.666667  81.444444   90.100000
std       3.02765   39.393864   68.507907   5.775641    8.116513
min       1.00000   65.000000   67.000000  72.000000   80.000000
25%       3.25000   76.500000   82.500000  78.250000   85.500000
50%       5.50000   86.500000   88.500000  80.722222   88.500000
75%       7.75000   95.166667   94.000000  85.750000   91.500000
max      10.00000  200.000000  300.000000  90.000000  110.000000

In [6]:
df['Math'] = df['Math'].clip(0,100)
df['Science'] = df['Science'].clip(0,100)
df['Attendance'] = df['Attendance'].clip(0,100)

In [7]:
Q1 = df[['Math','Science','English','Attendance']].quantile(0.25)
Q3 = df[['Math','Science','English','Attendance']].quantile(0.75)
IQR = Q3 - Q1

outliers = ((df[['Math','Science','English','Attendance']] < (Q1 - 1.5*IQR)) |
            (df[['Math','Science','English','Attendance']] > (Q3 + 1.5*IQR)))

outliers

    Math  Science  English  Attendance
0  False    False    False       False
1  False    False    False       False
2  False    False    False       False
3  False    False    False       False
4  False    False    False       False
5  False    False    False       False
6  False    False    False       False
7  False    False    False       False
8  False    False    False       False
9  False    False    False       False

In [8]:
df = df[~outliers.any(axis=1)]

In [9]:
df['Math_log'] = np.log(df['Math'])

In [10]:
df.head()
df.describe()

       Student_ID        Math    Science    English  Attendance   Math_log
count    10.00000   10.000000   10.00000  10.000000   10.000000  10.000000
mean      5.50000   84.888889   86.90000  81.444444   89.100000   4.431403
std       3.02765   12.383781   10.81614   5.775641    5.626327   0.150090
min       1.00000   65.000000   67.00000  72.000000   80.000000   4.174387
25%       3.25000   76.500000   82.50000  78.250000   85.500000   4.337227
50%       5.50000   86.500000   88.50000  80.722222   88.500000   4.459994
75%       7.75000   95.166667   94.00000  85.750000   91.500000   4.555126
max      10.00000  100.000000  100.00000  90.000000  100.000000   4.605170